Controllers/GenerateQRCodeController.cs
using Microsoft.AspNetCore.Mvc;
//using APELC.PublicShared;
using APELC.LocalShared;
using APELC.Model;
//using QRCoder;
using System.Drawing;
using System.Drawing.Imaging;

namespace APELC.Controllers
{
	public class GenerateQRCodeController : Controller
	{
        readonly static string _encryptCode = SecurityConstantsLocal.EncryptCode();

        public IActionResult Index()
        {
            string _ePUserId = HttpContext.Session.GetString("_userId") ?? "";
            if (_ePUserId != "")
            {
                MtdGetDashboardSession("");
                var config = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
                string _path01 = config["MySetting:ServerPathMain"];
                string _path = _path01;
                if (_path != null && _path.Length > 0)
                {
                    _path = '/' + _path01;
                }
                //var urlX = HttpContext.Request.GetEncodedUrl();
                //var url2 = HttpContext.Request.GetDisplayUrl();
                string _method = "MtdSkrinTimeLokasi";
                var url1 = HttpContext.Request.Scheme;
                var url2 = HttpContext.Request.Host;
                string _url = url1 + "://" + url2 + _path;
                ModelQRCode _data = new();
                string _anugerakPk = "1"; // GET VALUE FROM SYSTEM eg: AcaraProcess.MtdGetCurrentEventPk().ToString();
                string _getQrText = MtdGetCadanganQRText(_anugerakPk, _url, "", "", _method);
                _data.QRCodeText = _getQrText;
                _data.CEVENT = _anugerakPk;
                _data.CSEMAKMASA = "Y";
                return View(_data);
            }
            else
            {
                return Redirect("/Home/Index");
            }
        }
        private void MtdGetDashboardSession(string id)
        {
            HttpContext.Session.SetString("_titleTop", "QR Code Generate");
            HttpContext.Session.SetString("_titleSmall", "Index");
        }

        //[HttpPost]
        //public IActionResult MtdGetQRCode(ModelQRCode _data)
        //{
        //    string _inputText = _data.QRCodeText;
        //    if (_inputText != null && _inputText.Length > 0)
        //    {
        //        QRCodeGenerator QrGenerator = new QRCodeGenerator();
        //        QRCodeData QrCodeInfo = QrGenerator.CreateQrCode(_inputText, QRCodeGenerator.ECCLevel.Q);
        //        QRCode QrCode = new QRCode(QrCodeInfo);
        //        //Bitmap QrBitmap = QrCode.GetGraphic(60);
        //        //Bitmap QrBitmap = QrCode.GetGraphic(20, "#800000", "#FAEBD7");
        //        //Bitmap QrBitmap = QrCode.GetGraphic(20, Color.Maroon, Color.AntiqueWhite, (Bitmap)Bitmap.FromFile("C:\\logoUTMbw.jpg"));
        //        Bitmap QrBitmap = QrCode.GetGraphic(20, Color.Maroon, Color.AntiqueWhite, (Bitmap)Bitmap.FromFile("C:\\Log\\LogoUtm01.png"), 30);
        //        byte[] BitmapArray = QrBitmap.BitmapToByteArray();
        //        string QrUri = string.Format("data:image/png;base64,{0}", Convert.ToBase64String(BitmapArray));
        //        ViewBag.QrCodeUri = QrUri;
        //    }
        //    else
        //    {
        //        ViewBag.QrCodeUri = null;
        //    }
        //    return View("Index", _data);
        //}

        // GET AJAX : MtdGetQRCodeTextAjax
        [HttpPost]
        public JsonResult MtdGetQRCodeTextAjax([FromBody] ModelQRCode _carian)
        {
            string _ePUserId = HttpContext.Session.GetString("_userId") ?? "";
            if (_ePUserId != "")
            {
                string _eventFk = _carian.CEVENT ?? "0";
                string _masaMula = _carian.CMASA_MULA ?? "";
                string _masaTamt = _carian.CMASA_TAMAT ?? "";
                string _semak = _carian.CSEMAKMASA ?? "T"; // Value Y-T
                string _method = "MtdSkrinLokasi";
                if (_semak == "Y") _method = "MtdSkrinTimeLokasi";
                var url1 = HttpContext.Request.Scheme;
                var url2 = HttpContext.Request.Host;
                string _url = url1 + "://" + url2 + _carian.CPATH;
                string _getQrText = MtdGetCadanganQRText(_eventFk, _url, _masaMula, _masaTamt, _method);
                return Json(_getQrText);
            }
            else
            {
                return Json("");
            }
        }

        // GET AJAX : MtdGetQRCodeTextTimeAjax
        [HttpPost]
        public JsonResult MtdGetQRCodeTextTimeAjax([FromBody] ModelQRCode _carian)
        {
            string _ePUserId = HttpContext.Session.GetString("_userId") ?? "";
            if (_ePUserId != "")
            {
                string _eventFk = _carian.CEVENT ?? "0";
                string _masaMula = _carian.CMASA_MULA ?? "";
                string _masaTamt = _carian.CMASA_TAMAT ?? "";
                string _method = "MtdSkrinTimeLokasi";
                var url1 = HttpContext.Request.Scheme;
                var url2 = HttpContext.Request.Host;
                string _url = url1 + "://" + url2 + _carian.CPATH;
                string _getQrText = MtdGetCadanganQRText(_eventFk, _url, _masaMula, _masaTamt, _method);
                return Json(_getQrText);
            }
            else
            {
                return Json("");
            }
        }

        private string MtdGetCadanganQRText(string _eventFk, string _url, string _masaMula, string _masaTamat, string _method)
        {
            string _returnText = "";
            string _text = _masaMula + "~~~" + _masaTamat;
            //string _anugerakPkEnc = EncryptHr.NewEncrypt(_eventFk, _encryptCode);
            //string _timeEnc = EncryptHr.NewEncrypt(_text, _encryptCode);
            //_returnText = _url + "/Acara/MtdSkrinLokasi/" + _anugerakPkEnc + "&xlms=";
            //_returnText = _url + "/Acara/MtdSkrinTimeLokasi/" + _anugerakPkEnc + "&xlms=";
            //_returnText = _url + "/Acara/" + _method + "/" + _anugerakPkEnc + "&time=" + _timeEnc + "&xlms=";
            return _returnText;
        }
    }

    //Extension method to convert Bitmap to Byte Array
    public static class BitmapExtension
    {
//        public static byte[] BitmapToByteArray(this Bitmap bitmap)
//        {
//            using (MemoryStream ms = new MemoryStream())
//            {
//#pragma warning disable CA1416 // Validate platform compatibility
//                //bitmap.Save(ms, ImageFormat.Png);
//#pragma warning restore CA1416 // Validate platform compatibility
//                return ms.ToArray();
//            }
//        }
    }
}

Views/GenerateQRCode/Index.cshtml
@inject IHttpContextAccessor HttpContextAccessor
@inject IConfiguration Configuration
@* @model ModelQRCode *@
@{
	ViewData["Title"] = "Home Page";
#pragma warning disable CS8602
	string _userLogin = HttpContextAccessor.HttpContext.Session.GetString("_userId") ?? "";
#pragma warning restore CS8602
    var _path01 = Configuration.GetSection("MySetting")["ServerPathMain"] ?? "";
	var _path5 = _path01;
    if (_path5.Length > 1) {
        _path5 = '/' + _path01;
    }
}
<input type="hidden" id="IdPathServer" value="@_path5">
<div class="container-xxl">
	@using (Html.BeginForm("MtdGetQRCode", "GenerateQRCode", FormMethod.Post)){
		<div class="card shadow-sm">
			<div class="card-header cursor-pointer rotate" data-bs-toggle="collapse" data-bs-target="#IdCardCarian" style="background-color: antiquewhite;">
				<h3 class="card-title">
					<i class="fas fa-search fs-2x"></i>
					<span>&nbsp;&nbsp; QRCode Text Input</span>
				</h3>
			</div>
			<div class="card-body">
				<div class="row g-0">
					<div class="col-sm-12">
						<div class="form-floating mb-7 row">
						@* 	@Html.DropDownListFor(m => m.CEVENT, new SelectList(Model.ListEventMajlis, "KOD", "NAMA_PARAMETER"), "-- Please Select --", new { @class = "form-control text-maroon", id = "IdDdEventMajlis", style = "background-color: #d9fdfe;" }) *@
							<label for="floatingInput"><span class="required">Majlis Anugerah : </span></label>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-4">
						<div class="form-floating mb-7 me-7 row">
							@* @Html.TextBoxFor(m => m.CMASA_MULA, new { @class = "form-control text-maroon-bold", @id = "IdTextCMasaMula", style = "background-color: #d9fdfe;", @type="datetime-local", step="1"  }) *@
							<label for="floatingInput"><span class="required">Tarikh/Masa Mula</span></label>
						</div>
					</div>
					<div class="col-sm-4">
						<div class="form-floating mb-7 me-7 row">
							@* @Html.TextBoxFor(m => m.CMASA_TAMAT, new { @class = "form-control text-maroon-bold", @id = "IdTextCMasaTamat", style = "background-color: #d9fdfe;", @type="datetime-local", step="1"  }) *@
							<label for="floatingInput"><span class="required">Tarikh/Masa Tamat</span></label>
						</div>
					</div>
					<div class="col-sm-4">
						<div class="form-floating mb-7 row">
							@* @Html.DropDownListFor(m => m.CSEMAKMASA, new SelectList(Model.ListYaTidak, "KOD", "NAMA_PARAMETER"), "-- Please Select --", new { @class = "form-control text-maroon", id = "IdDdAdaSelaMasa", style = "background-color: #d9fdfe;" }) *@
							<label for="floatingInput"><span class="required">Semak Masa Slide</span></label>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-12">
						<div class="form-floating mb-7 row">
							@* @Html.TextBoxFor(m => m.QRCodeText, new { @class = "form-control text-maroon", @id = "IdQRText", style = "background-color: #FFFFFA;" }) *@
							<label for="floatingInput"><span>QR Code Text</span></label>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-12" style="text-align: center;">
						<button type="button" class="btn btn-sm btn-light-primary" id="IdBtnGenerateQRCOde"><i class="la la-qrcode fs-2x"></i> Generate QR Code</button>
						<button type="submit" class="btn btn-sm btn-primary" id="IdBtnGenerateQRCOdeCapai" formaction="@_path5/GenerateQRCode/MtdGetQRCode" style="display: none;">Generate QR Code</button>
					</div>
				</div>
			</div>
		</div>
		<div class="card">
			<div class="card-body">
				<div class="row">
					<div class="col-sm-12" style="text-align: center;">
						@if (ViewBag.QrCodeUri != null)
						{
							<img src="@ViewBag.QrCodeUri" style="width:400px; height: 400px" />
						}
					</div>
				</div>
		</div>
		</div>
	}
</div>

@section scripts
{
    <script src="~/js/QRCode/QRCode.js" type="text/javascript"></script>
}